### ISSUE TITLE
Feature request - Ground speed TLOD override

### ISSUE THREAD

**Issue by tabasc** [ResetXPDR/MSFS2020_AutoFPS#65]
Thanks so much for this excellent tool.

Fully understand if you are not interested in adding anymore features, however I would like to request a ground speed parameter if possible.

I use the program in the altitude steps mode as I find this is the least resource intensive mode.

The idea is that the TLOD should be only reduced to minimum after V1 until ~200ft, and during short final and landing.

These are the phases where smooth performance is absolutely critical.

However while taxing, having the TLOD minimum set very low (50), causes blurry textures in parts of the airport.

My proposed solution would be to add the ground speed parameter which overrides or increases the minimum TLOD when under a certain value (e.g. 50 knots).

Like I said, if this is not a simple addition or you are simply not interested in adding features with FS24 around the corner, completely understand, and thanks again for this tool which breathed new life into the sim for me. Even with top end hardware, stutters on short final can be extremely frustrating, and this tool solves that problem.

**Comment by ResetXPDR** [comment]
Earlier versions of this app allowed TLOD to change on the ground at low speeds but it exacerbated texture tearing issues when using DX12, a long standing bug with MSFS that is yet to be fixed. As a result, other than on initial flight load at an airport, the ability to change TLOD on the ground was removed. The only way I would ever reintroduce it is if Asobo fixes that bug, which is extremely unlikely given how long standing this bug has existed and the imminent release of MSFS 2024.

**Comment by tabasc** [comment]
Oh I see, thanks, wasn't aware of that.

According to the patch notes the DX12 ground texture bug was fixed in SU15:

![image](https://github.com/ResetXPDR/MSFS2020_AutoFPS/assets/67777719/28e03f75-f987-48f8-a67a-3a414d603642)

I haven't purposefully tested it, but I haven't encountered that texture bug since SU15 release. Posts on the forums suggest it is indeed fixed.

**Comment by ResetXPDR** [comment]
Interesting. I was monitoring the SU15 beta and it was still broken then so they must have fixed it last minute. In any case, the app is still currently closed for new features (even though this was an old feature now removed, it would have to be reworked in with the current app implementation) but I will keep it in mind if I do open up the app for further development in future.
